export const INFO_TYPES = {
    MEDICATION: 'MEDICATION',
    CONDITION: 'CONDITION',
    DISEASE: 'DISEASE',
    EXAM: 'EXAM',
    ALLERGY: 'ALLERGY',
    DIAGNOSES: 'DIAGNOSES' 
}

export const INSURANCE_TYPES = {
    UNIMED: 'UNIMED',
    HAPVIDA: 'HAPVIDA',
    BRADESCO: 'BRADESCO',
  }